services:
  - type: web
    name: tecsupfit
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      cd public/chatbot
      npm install
      npm run build
      cp -r dist/* .
    startCommand: php artisan migrate --force && php artisan serve --host 0.0.0.0 --port $PORT
    plan: free